2021-02-25 15:26:52,363 INFO    MainThread:14719 [wandb_setup.py:_flush():69] setting env: {}
2021-02-25 15:26:52,363 INFO    MainThread:14719 [wandb_setup.py:_flush():69] setting login settings: {}
2021-02-25 15:26:52,364 INFO    MainThread:14719 [wandb_setup.py:_flush():69] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fb35c14c310>
2021-02-25 15:26:52,364 INFO    MainThread:14719 [wandb_init.py:_log_setup():319] Logging user logs to /home/dacon/Dacon/bdg/ct/segment_abdomen/src/wandb/run-20210225_152652-2u23jg97/logs/debug.log
2021-02-25 15:26:52,364 INFO    MainThread:14719 [wandb_init.py:_log_setup():320] Logging internal logs to /home/dacon/Dacon/bdg/ct/segment_abdomen/src/wandb/run-20210225_152652-2u23jg97/logs/debug-internal.log
2021-02-25 15:26:52,364 INFO    MainThread:14719 [wandb_init.py:init():352] calling init triggers
2021-02-25 15:26:52,364 INFO    MainThread:14719 [wandb_init.py:init():359] wandb.init called with sweep_config: {}
config: {'path': '../data/normal2', 'name': 'efficientnet-b3', 'model': 'efficientnet-b3', 'pretrain': 'imagenet', 'model_path': '../models/efficientnet-b3', 'augmentation': [], 'num_epochs': 20, 'batch_size': 48, 'optimizer': <class 'torch.optim.adam.Adam'>, 'scheduler': <class 'torch.optim.lr_scheduler.CosineAnnealingWarmRestarts'>, 'loss': <class 'segmentation_models_pytorch.utils.losses.DiceLoss'>, 'seed': 1015, 'device': 'cuda'}
2021-02-25 15:26:52,364 INFO    MainThread:14719 [wandb_init.py:init():374] re-initializing run, found existing run on stack: mgcnx1bi
2021-02-25 15:26:52,365 INFO    MainThread:14719 [wandb_run.py:finish():1078] finishing run deagwon-bu/ct_segment/mgcnx1bi
2021-02-25 15:26:52,365 INFO    MainThread:14719 [wandb_init.py:_jupyter_teardown():250] cleaning up jupyter logic
2021-02-25 15:26:52,365 INFO    MainThread:14719 [jupyter.py:save_history():208] not saving jupyter history
2021-02-25 15:26:52,365 INFO    MainThread:14719 [wandb_run.py:_atexit_cleanup():1392] got exitcode: 0
2021-02-25 15:26:52,365 INFO    MainThread:14719 [wandb_run.py:_restore():1364] restore
2021-02-25 15:26:52,686 INFO    MainThread:14719 [wandb_run.py:_wait_for_finish():1515] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 854
  total_bytes: 854
}

2021-02-25 15:26:54,694 INFO    MainThread:14719 [wandb_run.py:_wait_for_finish():1515] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4916
  total_bytes: 4916
}

2021-02-25 15:26:56,697 INFO    MainThread:14719 [wandb_run.py:_wait_for_finish():1515] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4916
  total_bytes: 4916
}

2021-02-25 15:26:58,107 INFO    MainThread:14719 [wandb_run.py:_show_files():1737] logging synced files
2021-02-25 15:26:58,111 INFO    MainThread:14719 [wandb_init.py:init():401] starting backend
2021-02-25 15:26:58,111 INFO    MainThread:14719 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-02-25 15:26:58,113 INFO    MainThread:14719 [backend.py:ensure_launched():123] starting backend process...
2021-02-25 15:26:58,126 INFO    MainThread:14719 [backend.py:ensure_launched():128] started backend process with pid: 15070
2021-02-25 15:26:58,127 INFO    MainThread:14719 [wandb_init.py:init():406] backend started and connected
2021-02-25 15:26:58,139 INFO    MainThread:14719 [wandb_init.py:init():446] updated telemetry
2021-02-25 15:26:58,139 INFO    MainThread:14719 [wandb_init.py:init():465] communicating current version
2021-02-25 15:26:58,662 INFO    MainThread:14719 [wandb_init.py:init():470] got version response 
2021-02-25 15:26:58,662 INFO    MainThread:14719 [wandb_init.py:init():478] communicating run to backend with 30 second timeout
2021-02-25 15:26:59,009 INFO    MainThread:14719 [wandb_init.py:init():503] starting run threads in backend
2021-02-25 15:27:00,106 INFO    MainThread:14719 [wandb_run.py:_console_start():1422] atexit reg
2021-02-25 15:27:00,107 INFO    MainThread:14719 [wandb_run.py:_redirect():1285] redirect: SettingsConsole.WRAP
2021-02-25 15:27:00,107 INFO    MainThread:14719 [wandb_run.py:_redirect():1320] Wrapping output streams.
2021-02-25 15:27:00,107 INFO    MainThread:14719 [wandb_run.py:_redirect():1336] Redirects installed.
2021-02-25 15:27:00,107 INFO    MainThread:14719 [wandb_init.py:init():527] run started, returning control to user process
2021-02-25 15:27:23,011 INFO    MainThread:14719 [wandb_run.py:_atexit_cleanup():1392] got exitcode: 0
2021-02-25 15:27:23,012 INFO    MainThread:14719 [wandb_run.py:_restore():1364] restore
2021-02-25 15:27:23,295 INFO    MainThread:14719 [wandb_run.py:_wait_for_finish():1515] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 854
  total_bytes: 854
}

2021-02-25 15:27:25,303 INFO    MainThread:14719 [wandb_run.py:_wait_for_finish():1515] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4714
  total_bytes: 4714
}

2021-02-25 15:27:26,606 INFO    MainThread:14719 [wandb_run.py:_show_files():1737] logging synced files
